Smits={};Smits.Common={nodeIdIncrement:0,activeNode:0,roundFloat:function(a,b){for(var i=0,p=1;i<b;){p*=10;i++}return Math.round(a*p)/p},apply:function(a,b){if(a&&typeof b=="object")for(var i in b)a[i]=b[i];return a},addEventHandler:function(a,b,i,p){try{a.addEventListener(b,function(d){return function(y){p.e=y;d(p)}}(i,p),false)}catch(t){}}};
Smits.PhyloCanvas=function(){var a,b,i;return function(p,t,d,y,g){this.getNewickObject=function(){};this.clear=function(){};this.scale=function(u){i.svg.scale(u)};this.getSvg=function(){return i};this.getPhylogram=function(){return a};if(typeof p==="object")if(p.xml){p=p.fileSource?p.xml:XMLObjectifier.textToXML(p.xml);p=XMLObjectifier.xmlToJSON(p);dataObject=new Smits.PhyloCanvas.JsonParse(p)}else if(p.json)dataObject=new Smits.PhyloCanvas.JsonParse(p.json);else alert("Please set the format of input data");
else dataObject=new Smits.PhyloCanvas.NewickParse(p);b=t;i=new Smits.PhyloCanvas.Render.SVG(b,d,y);a=g=="circular"?new Smits.PhyloCanvas.Render.CircularPhylogram(i,dataObject):new Smits.PhyloCanvas.Render.Phylogram(i,dataObject)}}();Smits.PhyloCanvas.prototype={};Smits.PhyloCanvas.Node=function(){return function(a,b){this.id=Smits.Common.nodeIdIncrement+=1;this.newickLen=this.len=this.level=0;this.type=this.name="";this.chart={};a&&Smits.Common.apply(this,a);this.children=[];b&&b.children.push(this)}}();
Smits.PhyloCanvas.Node.prototype={getCountAllChildren:function(){var a=0;for(var b in this.children){var i=this.children[b];if(i.children&&i.children.length>0)a+=i.getCountAllChildren();else a++}return a},getCountImmediateChildren:function(){var a=0;for(var b in this.children)a+=this.children[b].length;return a},getMidbranchPosition:function(){for(var a=[0,0],b=0;b<this.children.length;b++){var i=this.children[b];if(i.children&&i.children.length>0)if(b==0){a[0]=i.getMidbranchPosition();a[1]+=i.getCountAllChildren()}else a[1]+=
b==this.children.length-1?i.getMidbranchPosition():i.getCountAllChildren();else{if(b==0)a[0]=1;a[1]+=1}}return a[1]>=a[0]?(a[1]-a[0])/2+a[0]:a[0]}};
Smits.PhyloCanvas.NewickParse=function(){var a,b,i,p=0,t=0,d,y=function(h){for(var c=new Smits.PhyloCanvas.Node;b!==")"&&b!==",";)if(b===":"){f();c.len=Smits.Common.roundFloat(u(),4);if(c.len==0)c.len=1.0E-4}else if(b==="'"||b==='"'){c.type="label";c.name=F(b)}else{c.type="label";c.name=u()}c.level=h.level+1;return c},g=function(h){var c=new Smits.PhyloCanvas.Node;if(h)c.level=h.level+1;for(;b!==")";){f();b==="("?c.children.push(g(c)):c.children.push(y(c))}f();if(b!==":"&&b!==")"&&b!==","&&b!==";"){c.type=
"label";c.name=u()}if(b===":"){f();c.len=Smits.Common.roundFloat(u(),4);if(c.len==0)c.len=1.0E-4;c.type="stem"}return c},u=function(){for(var h="";b!==":"&&b!==")"&&b!==","&&b!==";";){h+=b;f()}return h},F=function(h){for(var c="";b!==h;){c+=b;f()}return c},f=function(){b=a.charAt(i);i+=1;return b},m=function(h){if(h.children&&h.children.length)for(var c=0;c<h.children.length;c++){var e=h.children[c];if(e.len===0)e.len=1;e.newickLen=Smits.Common.roundFloat(e.len+h.newickLen,4);if(e.level>p)p=e.level;
if(e.newickLen>t)t=e.newickLen;e.children.length>0&&m(e,h)}return h};return function(h){this.getRoot=function(){return d};this.getLevels=function(){return p};this.getNewickLen=function(){return t};this.getValidate=function(){};a=h;i=0;f();d=g();d=m(d)}}();Smits.PhyloCanvas.NewickParse.prototype={};
Smits.PhyloCanvas.JsonParse=function(){var a=0,b=0,i,p,t=function(d,y){var g=new Smits.PhyloCanvas.Node;if(y)g.level=y.level+1;if(d.clade&&d.clade.length)for(var u=0;u<d.clade.length;u++)g.children.push(t(d.clade[u],g));if(d.branch_length){if(typeof d.branch_length==="object")d.branch_length=d.branch_length[0].Text;g.len=Smits.Common.roundFloat(d.branch_length,4);if(g.len==0)g.len=1.0E-4}if(d.name){g.type="label";g.name=d.name[0].Text}if(d.sequence&&d.sequence[0]&&d.sequence[0].name&&d.sequence[0].name[0]&&
d.sequence[0].name[0].Text)g.sequenceName=d.sequence[0].name[0].Text;if(d.taxonomy&&d.taxonomy[0]){if(d.taxonomy[0].scientific_name&&d.taxonomy[0].scientific_name[0]&&d.taxonomy[0].scientific_name[0].Text)g.taxonomyScientificName=d.taxonomy[0].scientific_name[0].Text;if(d.taxonomy[0].common_name&&d.taxonomy[0].common_name[0]&&d.taxonomy[0].common_name[0].Text)g.taxonomyCommonName=d.taxonomy[0].common_name[0].Text}if(d.sequence&&d.sequence[0]&&d.sequence[0].accession&&d.sequence[0].accession[0]&&d.sequence[0].accession[0].Text)g.sequenceAccession=
d.sequence[0].accession[0].Text;if(d.point)g.LatLong=[d.point[0].lat[0].Text,d.point[0]["long"][0].Text];if(!g.name){if(g.sequenceName)g.name=g.sequenceName;else if(g.taxonomyScientificName)g.name=g.taxonomyScientificName;else if(g.taxonomyCommonName)g.name=g.taxonomyCommonName;else if(g.sequenceAccession)g.name=g.sequenceAccession;if(g.name)g.type="label"}if(d.annotation){if(d.annotation[0]&&d.annotation[0].desc&&d.annotation[0].desc[0]&&d.annotation[0].desc[0].Text)g.description=d.annotation[0].desc[0].Text;
if(d.annotation[0]&&d.annotation[0].uri&&d.annotation[0].uri[0]&&d.annotation[0].uri[0].Text)g.uri=d.annotation[0].uri[0].Text}if(d.chart)if(d.chart[0])for(u in d.chart[0])if(u!="Text"&&u!="_children")g.chart[u]=d.chart[0][u][0].Text;if(g&&g.level>1)g.len||(p="Error. Please include Branch Lengths - we only draw rooted phylogenetic trees.");return g};recursiveProcessRoot=function(d){if(d.children&&d.children.length)for(var y=0;y<d.children.length;y++){var g=d.children[y];g.newickLen=Math.round((g.len+
d.newickLen)*1E4)/1E4;if(g.level>a)a=g.level;if(g.newickLen>b)b=g.newickLen;g.children.length>0&&recursiveProcessRoot(g,d)}return d};recursiveProcessParameters=function(d,y){for(var g in d)if(g!="_children"&&g!="Text")if(g=="rectangular"||g=="circular")recursiveProcessParameters(d[g][0],g);else{Smits.PhyloCanvas.Render.Parameters[g]||(Smits.PhyloCanvas.Render.Parameters[g]={});Smits.PhyloCanvas.Render.Parameters.set(g,d[g][0].Text,y)}};return function(d){this.getRoot=function(){return i};this.getLevels=
function(){return a};this.getNewickLen=function(){return b};this.getValidate=function(){return p};u=d;if(d.phylogeny&&d.phylogeny[0]&&d.phylogeny[0].clade)i=t(d.phylogeny[0].clade[0]);if(d.phylogeny&&d.phylogeny[0]&&d.phylogeny[0].render&&d.phylogeny[0].render[0]){if((d=d.phylogeny[0].render[0])&&d.styles){var y=d.styles[0];for(var g in y)if(g!="_children"&&g!="Text"){Smits.PhyloCanvas.Render.Style[g]||(Smits.PhyloCanvas.Render.Style[g]={});for(var u in y[g][0])if(u!="_attributes")Smits.PhyloCanvas.Render.Style[g][u.replace("_",
"-")]=y[g][0][u]}}d&&d.parameters&&recursiveProcessParameters(d.parameters[0]);if(d&&d.charts){d=d.charts[0];for(g in d)if(g!="_children"&&g!="Text")for(u in d[g])if(d[g][u].type=="binary"){d[g][u].chart=g;Smits.PhyloCanvas.Render.Parameters.binaryCharts.push(d[g][u])}else if(d[g][u].type=="bar"){d[g][u].chart=g;Smits.PhyloCanvas.Render.Parameters.barCharts.push(d[g][u])}}}i=recursiveProcessRoot(i)}}();Smits.PhyloCanvas.JsonParse.prototype={};Smits.PhyloCanvas.Render={};
Smits.PhyloCanvas.Render.Style={line:{stroke:"rgb(0,0,0)","stroke-width":1},text:{"font-family":"Verdana","font-size":12,"text-anchor":"start"},path:{stroke:"rgb(0,0,0)","stroke-width":1},connectedDash:{stroke:"rgb(200,200,200)","stroke-dasharray":". "},textSecantBg:{fill:"#EEE",stroke:"#DDD"},highlightedEdgeCircle:{fill:"red"},barChart:{fill:"#003300",stroke:"#DDD"},getStyle:function(a,b){return this[a]?this[a]:this[b]}};
Smits.PhyloCanvas.Render.Parameters={jsOverride:0,Rectangular:{bufferX:200,bufferY:40,bufferInnerLabels:10,bufferOuterLabels:5,minHeightBetweenLeaves:10,alignRight:false},Circular:{bufferRadius:0.33,bufferAngle:20,initStartAngle:160,innerCircleRadius:0,minHeightBetweenLeaves:5,bufferInnerLabels:2,bufferOuterLabels:5},binaryCharts:[],barCharts:[],binaryChartBufferInner:5,binaryChartBufferSiblings:0.01,binaryChartThickness:15,binaryChartDisjointed:false,barChartBufferInner:3,barChartHeight:50,barChartWidth:0.5,
mouseRollOver:function(a){if(a.node.edgeCircleHighlight)a.node.edgeCircleHighlight.show();else{var b=a.svg.draw(new Smits.PhyloCanvas.Render.Circle(a.x,a.y,5,{attr:Smits.PhyloCanvas.Render.Style.highlightedEdgeCircle}));a.node.edgeCircleHighlight=b[0]}a.textEl.attr({fill:"red"})},mouseRollOut:function(a){a.node.edgeCircleHighlight.hide();a.textEl.attr({fill:"#000"})},set:function(a,b,i){if(!this.jsOverride)if(i)if(i=="circular")this.Circular[a]=parseFloat(b);else{if(i=="rectangular")this.Rectangular[a]=
parseFloat(b)}else this[a]=parseFloat(b)}};Smits.PhyloCanvas.Render.Line=function(){return function(a,b,i,p,t){this.type="line";this.x1=a;this.x2=b;this.y1=i;this.y2=p;if(t){Smits.Common.apply(this,t);if(t.attr)this.attr=t.attr}}}();Smits.PhyloCanvas.Render.Text=function(){return function(a,b,i,p){this.type="text";this.x=a;this.y=b;this.text=i;if(p){Smits.Common.apply(this,p);if(p.attr)this.attr=p.attr}}}();
Smits.PhyloCanvas.Render.Path=function(){return function(a,b){this.type="path";this.path=a;if(b){Smits.Common.apply(this,b);if(b.attr)this.attr=b.attr}}}();Smits.PhyloCanvas.Render.Circle=function(){return function(a,b,i,p){this.type="circle";this.x=a;this.y=b;this.radius=i;if(p){Smits.Common.apply(this,p);if(p.attr)this.attr=p.attr}}}();Smits.PhyloCanvas.Render.SVG=function(){return function(a,b,i){this.canvasSize=[b,i];this.svg=Raphael(a,this.canvasSize[0],this.canvasSize[1])}}();
Smits.PhyloCanvas.Render.SVG.prototype={render:function(){for(var a=this.phylogramObject.getDrawInstructs(),b=0;b<a.length;b++)if(a[b].type=="line")this.svg.path(["M",a[b].x1,a[b].y1,"L",a[b].x2,a[b].y2]).attr(Smits.PhyloCanvas.Render.Style.line);else if(a[b].type=="path")this.svg.path(a[b].path).attr(a[b].attr);else if(a[b].type=="circle")this.svg.circle(a[b].x,a[b].y,a[b].radius).attr({stroke:"red"});else{var i=this.svg.text(a[b].x,a[b].y,a[b].text).attr(Smits.PhyloCanvas.Render.Style.text);a[b].attr&&
i.attr(a[b].attr);a[b].rotate&&i.rotate(a[b].rotate);i=i.getBBox();Math.sqrt(i.height*i.height+i.width*i.width)}},draw:function(a){var b,i;if(a.type=="line")b=this.svg.path(["M",a.x1,a.y1,"L",a.x2,a.y2]).attr(Smits.PhyloCanvas.Render.Style.line);else if(a.type=="path")b=this.svg.path(a.path).attr(a.attr);else if(a.type=="circle")b=this.svg.circle(a.x,a.y,a.radius).attr({stroke:"red"});else if(a.type=="text"){b=this.svg.text(a.x,a.y,a.text).attr(Smits.PhyloCanvas.Render.Style.text);a.attr&&b.attr(a.attr);
a.rotate&&b.rotate(a.rotate);a=b.getBBox();i=Math.sqrt(a.height*a.height+a.width*a.width)}return[b,i]}};
Smits.PhyloCanvas.Render.Phylogram=function(){function a(n,r,q,w){return["M",n,r,"L",q,r,"L",q,w,"L",n,w,"Z"]}function b(n,r){if(n.len)if(h)h=false;else if(n.children.length==0)c=Smits.Common.roundFloat(c+F,4);if(n.children.length>0){var q=[],w,v,A,B;if(n.len){w=r;v=r=Smits.Common.roundFloat(r+u*n.len,4);B=A=c+n.getMidbranchPosition()*F;t.draw(new Smits.PhyloCanvas.Render.Line(w,v,A,B))}n.name&&t.draw(new Smits.PhyloCanvas.Render.Text(v+5,B,n.name));if(n.children&&n.children.length)for(v=0;v<n.children.length;v++)q.push(b(n.children[v],
r));n=[];for(v=0;v<q.length;v++){q[v][0]&&n.push(q[v][0]);q[v][1]&&n.push(q[v][1])}q=Math.min.apply(null,n);n=Math.max.apply(null,n);t.draw(new Smits.PhyloCanvas.Render.Path(["M",r+1.0E-4,q,"L",r,q,"L",r,n,"L",r+1.0E-4,n]))}else{w=r;v=Smits.Common.roundFloat(r+u*n.len,2);B=A=c;n.y=c;G.push(n);t.draw(new Smits.PhyloCanvas.Render.Line(w,v,A,B));d.alignRight&&t.draw(new Smits.PhyloCanvas.Render.Path(["M",v,A,"L",f,B],{attr:Smits.PhyloCanvas.Render.Style.connectedDash}));if(n.name){r={};r["text-anchor"]=
"start";if(n.uri)r.href=n.uri;if(n.description)r.title=n.description;r=t.draw(new Smits.PhyloCanvas.Render.Text(d.alignRight?f+d.bufferInnerLabels:v+d.bufferInnerLabels,B,n.name,{attr:r}));e=Math.max(r[1],e);Smits.PhyloCanvas.Render.Parameters.mouseRollOver&&Smits.Common.addEventHandler(r[0].node,"mouseover",Smits.PhyloCanvas.Render.Parameters.mouseRollOver,{svg:t,node:n,x:v,y:B,textEl:r[0]});Smits.PhyloCanvas.Render.Parameters.mouseRollOut&&Smits.Common.addEventHandler(r[0].node,"mouseout",Smits.PhyloCanvas.Render.Parameters.mouseRollOut,
{svg:t,node:n,x:v,y:B,textEl:r[0]});Smits.PhyloCanvas.Render.Parameters.onClickAction&&Smits.Common.addEventHandler(r[0].node,"mouseout",Smits.PhyloCanvas.Render.Parameters.onClickAction,{svg:t,node:n,x:v,y:B,textEl:r[0]})}}return[A,B]}function i(n,r,q){var w=(q&&q.bufferInner?q.bufferInner:0)|Smits.PhyloCanvas.Render.Parameters.binaryChartBufferInner,v=(q&&q.bufferSiblings?q.bufferSiblings*F:0)|(Smits.PhyloCanvas.Render.Parameters.binaryChartBufferSiblings<1?F*Smits.PhyloCanvas.Render.Parameters.binaryChartBufferSiblings:
Smits.PhyloCanvas.Render.Parameters.binaryChartBufferSiblings);q=(q&&q.thickness?q.thickness:0)|Smits.PhyloCanvas.Render.Parameters.binaryChartThickness;for(var A=0;A<G.length;A++){var B=G[A];t.draw(new Smits.PhyloCanvas.Render.Path(a(n+w,B.y-F/2+v/2,n+w+q,B.y+F/2-v/2),{attr:Smits.PhyloCanvas.Render.Style.getStyle(B.chart[r],"textSecantBg")}))}return n+w+q}function p(n,r,q){var w=[],v=q&&q.bufferInner?q.bufferInner:0|Smits.PhyloCanvas.Render.Parameters.barChartBufferInner,A=q&&q.height?q.height:0|
Smits.PhyloCanvas.Render.Parameters.barChartHeight;q=q&&q.width?q.width<1?F*q.width:q.width:0|(Smits.PhyloCanvas.Render.Parameters.barChartWidth<1?F*Smits.PhyloCanvas.Render.Parameters.barChartWidth:Smits.PhyloCanvas.Render.Parameters.barChartWidth);for(var B=0,H=0;H<G.length;H++)w.push(G[H].chart[r]);w=Math.max.apply(null,w);B=Smits.Common.roundFloat(A/w,4);for(H=0;H<G.length;H++){w=G[H];t.draw(new Smits.PhyloCanvas.Render.Path(a(n+v,w.y-q/2,n+v+B*w.chart[r],w.y+q/2),{attr:Smits.PhyloCanvas.Render.Style.getStyle(w.chart[r],
"barChart")}))}return n+v+A}var t,d=Smits.PhyloCanvas.Render.Parameters.Rectangular,y,g,u,F,f,m,h=true,c=0,e=0,l,x,G=[];return function(n,r){this.getCanvasSize=function(){return[y,g]};this.getRoot=function(){return r.getRoot()};r.getValidate()&&t.draw(0,0,r.getValidate());t=n;n=r.getRoot();var q=r.getNewickLen();y=t.canvasSize[0];g=t.canvasSize[1];l=d.bufferX;x=d.bufferY;m=d.minHeightBetweenLeaves;u=Math.round((y-l)/q);F=Math.round((g-x)/n.getCountAllChildren());if(F<m)F=m;f=Math.round(y-l);if(Smits.PhyloCanvas.Render.Parameters.binaryCharts.length||
Smits.PhyloCanvas.Render.Parameters.barCharts.length)d.alignRight=true;b(n,0);outerX=f+e+d.bufferInnerLabels;if(Smits.PhyloCanvas.Render.Parameters.binaryCharts.length){n=Smits.PhyloCanvas.Render.Parameters.binaryCharts;for(var w in n)outerX=i(outerX,n[w].chart,n[w])}if(Smits.PhyloCanvas.Render.Parameters.barCharts.length){n=Smits.PhyloCanvas.Render.Parameters.barCharts;for(w in n)outerRadius=p(outerX,n[w].chart,n[w])}}}();Smits.PhyloCanvas.Render.Phylogram.prototype={};
Smits.PhyloCanvas.Render.CircularPhylogram=function(){function a(k,o){o+=L;return[Smits.Common.roundFloat(q+k*Math.sin(o*M),4),Smits.Common.roundFloat(w+k*Math.cos(o*M),4)]}function b(k,o,j,s){var z=a(k,o),D=a(k,j),E=[],C=0;o=Math.abs(p(j-o))>180?1:-1;if(s&&s.invertSecant){o*=-1;C=1}s&&s.noMove||E.push("M");E.push(z[0],z[1],"A",k,k,0,o<1?0:1,C,D[0],D[1]);return E}function i(k,o,j,s){var z=[];o=a(o,k);k=a(j,k);s&&s.noMove||z.push("M");z.push(o[0],o[1],"L",k[0],k[1]);return z}function p(k){for(;k>360||
k<0;)if(k>360)k-=360;else if(k<0)k+=360;return k}function t(k,o,j,s){return y("M",b(k,j,s,{noMove:1,invertSecant:0}),"L",b(o,s,j,{noMove:1,invertSecant:1}),"Z")}function d(k,o){o=o;if(k.len)if(n){r=B|1;n=false}else if(k.children.length==0)r=Smits.Common.roundFloat(r+x,4);if(k.children.length>0){var j=[],s,z,D;s=o;z=o+=Smits.Common.roundFloat(l*k.len,4);if(k.children&&k.children.length)for(var E=0;E<k.children.length;E++){var C=d(k.children[E],o);C>0&&j.push(C)}E=Smits.Common.roundFloat(Math.min.apply(null,
j),4);j=Smits.Common.roundFloat(Math.max.apply(null,j),4);f.draw(new Smits.PhyloCanvas.Render.Path(y("M",a(o+0.01,E),"L",b(o,E,j,{noMove:true}),"L",a(o+0.01,j))));if(k.len){D=Smits.Common.roundFloat(E+(j-E)/2,4);f.draw(new Smits.PhyloCanvas.Render.Path(i(D,s,z)))}}else{k.y=r;A.push(k);s=o;z=Smits.Common.roundFloat(o+l*k.len);D=r;f.draw(new Smits.PhyloCanvas.Render.Path(i(D,s,z)));f.draw(new Smits.PhyloCanvas.Render.Path(i(D,z,v),{attr:Smits.PhyloCanvas.Render.Style.connectedDash}));if(k.name){o=a(v+
m.bufferInnerLabels,D);s=p(91-D-L);if(s>90&&s<270){s+=180;alignment="end"}else alignment="start";j={};j["text-anchor"]=alignment;if(k.uri)j.href=k.uri;if(k.description)j.title=k.description;s=f.draw(new Smits.PhyloCanvas.Render.Text(o[0],o[1],k.name,{attr:j,rotate:[s,o[0],o[1]]}));o=a(z,D);Smits.PhyloCanvas.Render.Parameters.mouseRollOver&&Smits.Common.addEventHandler(s[0].node,"mouseover",Smits.PhyloCanvas.Render.Parameters.mouseRollOver,{svg:f,node:k,x:o[0],y:o[1],textEl:s[0]});Smits.PhyloCanvas.Render.Parameters.mouseRollOut&&
Smits.Common.addEventHandler(s[0].node,"mouseout",Smits.PhyloCanvas.Render.Parameters.mouseRollOut,{svg:f,node:k,x:o[0],y:o[1],textEl:s[0]});Smits.PhyloCanvas.Render.Parameters.onClickAction&&Smits.Common.addEventHandler(s[0].node,"click",Smits.PhyloCanvas.Render.Parameters.onClickAction,{svg:f,node:k,x:o[0],y:o[1],textEl:s[0]});K=Math.max(s[1],K)}}return D}function y(k){for(var o=k,j=1;j<arguments.length;j++)o=o.concat(arguments[j]);return o}function g(){var k=[];k=t(v,v+K+m.bufferOuterLabels,(B|
1)+x/2,360+x/2+0.999);f.draw(new Smits.PhyloCanvas.Render.Path(k,{attr:Smits.PhyloCanvas.Render.Style.textSecantBg}))[0].toBack();return v+K+m.bufferOuterLabels}function u(k,o,j){var s=(j&&j.bufferInner?j.bufferInner:0)|Smits.PhyloCanvas.Render.Parameters.binaryChartBufferInner,z=(j&&j.bufferSiblings?j.bufferSiblings*x:0)|(Smits.PhyloCanvas.Render.Parameters.binaryChartBufferSiblings<1?x*Smits.PhyloCanvas.Render.Parameters.binaryChartBufferSiblings:Smits.PhyloCanvas.Render.Parameters.binaryChartBufferSiblings),
D=(j&&j.thickness?j.thickness:0)|Smits.PhyloCanvas.Render.Parameters.binaryChartThickness;j=(j&&j.disjointed?j.disjointed:false)|Smits.PhyloCanvas.Render.Parameters.binaryChartDisjointed;for(var E=true,C,I=0;I<A.length;I++){var J=A[I];if(!A[I+1]||J.chart[o]!==A[I+1].chart[o]||j){f.draw(new Smits.PhyloCanvas.Render.Path(t(k+s,k+s+D,(C?C:J.y)-x/2+(E&&!j?0:z/2),J.y+x/2-(I==A.length-1&&!j?0:z/2)),{attr:Smits.PhyloCanvas.Render.Style.getStyle(J.chart[o],"textSecantBg")}));C=0}else if(!C)C=J.y;E=false}return k+
s+D}function F(k,o,j){var s=[],z=j&&j.bufferInner?j.bufferInner:0|Smits.PhyloCanvas.Render.Parameters.barChartBufferInner,D=j&&j.height?j.height:0|Smits.PhyloCanvas.Render.Parameters.barChartHeight;j=j&&j.width?j.width<1?x*j.width:j.width:0|(Smits.PhyloCanvas.Render.Parameters.barChartWidth<1?x*Smits.PhyloCanvas.Render.Parameters.barChartWidth:Smits.PhyloCanvas.Render.Parameters.barChartWidth);for(var E=0,C=0;C<A.length;C++)s.push(A[C].chart[o]);s=Math.max.apply(null,s);E=Smits.Common.roundFloat(D/
s,4);for(C=0;C<A.length;C++){s=A[C];f.draw(new Smits.PhyloCanvas.Render.Path(t(k+z,k+z+E*s.chart[o],s.y-j/2,s.y+j/2),{attr:Smits.PhyloCanvas.Render.Style.getStyle(s.chart[o],"barChart")}))}return k+z+D}var f,m=Smits.PhyloCanvas.Render.Parameters.Circular,h,c,e,l,x,G,n=true,r=0,q,w,v,A=[],B,H,K=0,L,M=Math.PI/180;return function(k,o,j){this.getCanvasSize=function(){return[h,c]};this.getRoot=function(){return o.getRoot()};if(o.getValidate())k.draw({type:"text",x:0,y:k.canvasSize[1]/3,text:o.getValidate()});
else{f=k;k=o.getRoot();var s=o.getNewickLen();h=f.canvasSize[0];c=f.canvasSize[1];q=h/2;w=c/2;e=Math.min.apply(null,[h,c]);j=m.bufferRadius>1?m.bufferRadius:Smits.Common.roundFloat(e*m.bufferRadius,4);B=m.bufferAngle;G=m.innerCircleRadius;L=m.initStartAngle;v=Math.round((e-j-G)/2);l=(v-G)/s;x=Smits.Common.roundFloat((360-B)/k.getCountAllChildren(),4);d(k,G);H=g();if(Smits.PhyloCanvas.Render.Parameters.binaryCharts.length){j=Smits.PhyloCanvas.Render.Parameters.binaryCharts;for(var z in j)H=u(H,j[z].chart,
j[z])}if(Smits.PhyloCanvas.Render.Parameters.barCharts.length){j=Smits.PhyloCanvas.Render.Parameters.barCharts;for(z in j)H=F(H,j[z].chart,j[z])}}}}();Smits.PhyloCanvas.Render.CircularPhylogram.prototype={};
var XMLObjectifier=function(){var a=function(b){var i="";if(b&&typeof b==="string")i=b;return/^((-)?([0-9]*)((\.{0,1})([0-9]+))?$)/.test(i)};return{xmlToJSON:function(b){try{if(!b)return null;var i={};i.typeOf="JSXBObject";var p=b.nodeType==9?b.documentElement:b;i.RootName=p.nodeName||"";if(b.nodeType==3||b.nodeType==4)return b.nodeValue;var t=function(f){return f.replace(/^\s+|\s+$/gm,"")},d=function(f){return String(f).replace(/-/g,"_")},y=function(f,m){if(m.attributes.length>0){var h=m.attributes.length-
1,c;f._attributes=[];do{c=String(d(m.attributes[h].name));f._attributes.push(c);f[c]=t(m.attributes[h].value)}while(h--)}};(function(){return{activate:function(){var f=[];if(f){f.getNodesByAttribute=function(m,h){if(f&&f.length>0){var c=[],e,l=f.length-1;try{do{e=f[l];e[m]===h&&c.push(e)}while(l--);c.reverse();return c}catch(x){return null}}};f.getNodeByAttribute=function(m,h){if(f&&f.length>0){var c,e=f.length-1;try{do{c=f[e];if(c[m]===h)return c}while(e--)}catch(l){return null}return null}};f.getNodesByValue=
function(m){if(f&&f.length>0){var h=[],c,e=f.length-1;try{do{c=f[e];c.Text&&c.Text===m&&h.push(c)}while(e--);return h}catch(l){return null}}};f.contains=function(m,h){if(f&&f.length>0){var c=f.length-1;try{do if(f[c][m]===h)return true;while(c--)}catch(e){return false}return false}};f.indexOf=function(m,h){var c=-1;if(f&&f.length>0){var e=f.length-1;try{do if(f[e][m]===h)c=e;while(e--)}catch(l){return-1}return c}};f.SortByAttribute=function(m,h){if(f&&f.length>0){var c=function(e,l){e=e[l];return e=
bam.validation.isNumeric(e)?parseFloat(e):e};f.sort(function(e,l){e=c(e,m);l=c(l,m);l=e<l?-1:l<e?1:0;if(h)l=h.toUpperCase()==="DESC"?0-l:l;return l})}};f.SortByValue=function(m){if(f&&f.length>0){var h=function(c){c=c.Text;return c=bam.validation.isNumeric(c)?parseFloat(c):c};f.sort(function(c,e){c=h(c);e=h(e);e=c<e?-1:e<c?1:0;if(m)e=m.toUpperCase()==="DESC"?0-e:e;return e})}};f.SortByNode=function(m,h){if(f&&f.length>0){var c=function(e,l){e=e[l][0].Text;return e=bam.validation.isNumeric(e)?parseFloat(e):
e};f.sort(function(e,l){e=c(e,m);l=c(l,m);l=e<l?-1:l<e?1:0;if(h)l=h.toUpperCase()==="DESC"?0-l:l;return l})}}}return f}}})();var g=function(f){f.getNodeByAttribute=function(m,h){if(this.length>0){var c,e=this.length-1;try{do{c=this[e];if(c[m]==h)return c}while(e--)}catch(l){return false}return false}};f.contains=function(m,h){if(this.length>0){var c=this.length-1;try{do if(this[c][m]==h)return true;while(c--)}catch(e){return false}return false}};f.indexOf=function(m,h){var c=-1;if(this.length>0){var e=
this.length-1;try{do if(this[e][m]==h)c=e;while(e--)}catch(l){return-1}return c}};f.SortByAttribute=function(m,h){if(this.length){var c=function(e,l){e=e[l];return e=a(e)?parseFloat(e):e};this.sort(function(e,l){var x=0;e=c(e,m);l=c(l,m);if(e<l)x=-1;else if(l<e)x=1;if(h)x=h.toUpperCase()=="DESC"?0-x:x;return x})}};f.SortByValue=function(m){if(this.length){var h=function(c){c=c.Text;return c=a(c)?parseFloat(c):c};this.sort(function(c,e){var l=0;c=h(c);e=h(e);if(c<e)l=-1;else if(e<c)l=1;if(m)l=m.toUpperCase()==
"DESC"?0-l:l;return l})}};f.SortByNode=function(m,h){if(this.length){var c=function(e,l){e=e[l][0].Text;return e=a(e)?parseFloat(e):e};this.sort(function(e,l){var x=0;e=c(e,m);l=c(l,m);if(e<l)x=-1;else if(l<e)x=1;if(h)x=h.toUpperCase()=="DESC"?0-x:x;return x})}}},u=function(f,m){var h,c,e,l="";if(!m)return null;m.attributes.length>0&&y(f,m);f.Text="";if(m.hasChildNodes()){var x=m.childNodes.length-1,G=0;do{c=m.childNodes[G];switch(c.nodeType){case 1:f._children=[];h=c.localName?c.localName:c.baseName;
h=d(h);l!=h&&f._children.push(h);f[h]||(f[h]=[]);e={};f[h].push(e);c.attributes.length>0&&y(e,c);f[h].contains||g(f[h]);l=h;c.hasChildNodes()&&u(e,c);break;case 3:f.Text+=t(c.nodeValue);break;case 4:f.Text+=c.text?t(c.text):t(c.nodeValue);break}}while(G++<x)}};u(i,p);p=b=null;return i}catch(F){return null}},textToXML:function(b){var i=null;try{i=document.all?new ActiveXObject("Microsoft.XMLDOM"):new DOMParser;i.async=false}catch(p){throw new Error("XML Parser could not be instantiated");}var t;try{t=
document.all?i.loadXML(b)?i:false:i.parseFromString(b,"text/xml")}catch(d){throw new Error("Error parsing XML string");}return t}}}();
